version: '3'
services:
  my_postgres:
    image: postgres:latest
    container_name: next_tur
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superUser
      POSTGRES_PASSWORD: eYux2e3e
      POSTGRES_DB: next_tur
volumes:
  pgdata:
    driver: local